[package]
name = "jpng"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.22", features = ["derive", "cargo"] }
image = "0.25.2"
rayon = "1.10.0"
walkdir = "2.5.0"
